services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: hevo
      POSTGRES_PASSWORD: hevo
      POSTGRES_DB: hevo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      target: development
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://hevo:hevo@db:5432/hevo
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

  celery-worker:
    build:
      context: .
      target: development
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://hevo:hevo@db:5432/hevo
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

  celery-beat:
    build:
      context: .
      target: development
    command: celery -A config beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://hevo:hevo@db:5432/hevo
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
