# Generated by Django 6.0.8 on 2026-08-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_venuemembership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venuemembership",
            name="role",
            field=models.CharField(choices=[("owner", "Proprietário"), ("manager", "Gerente"), ("salesperson", "Vendedor")], max_length=20),
        ),
    ]
