# Generated by Django 6.0.8 on 2026-08-05 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("venue", "0003_alter_menuitem_category_alter_openinghours_weekday"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plan_name", models.CharField(max_length=100)),
                ("monthly_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(choices=[("trialing", "Em teste"), ("active", "Ativa"), ("past_due", "Pagamento pendente"), ("canceled", "Cancelada")], default="trialing", max_length=20)),
                ("started_at", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("venue", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="subscription", to="venue.venue")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
