# Generated by Django 6.0.8 on 2026-08-04 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conversation", "0001_initial"),
        ("venue", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarConnection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(choices=[("google", "Google Calendar")], default="google", max_length=20)),
                ("calendar_id", models.CharField(max_length=255)),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("token_expires_at", models.DateTimeField()),
                ("venue", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="calendar_connection", to="venue.venue")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("customer_name", models.CharField(blank=True, max_length=255)),
                ("customer_phone", models.CharField(max_length=20)),
                ("event_date", models.DateField(blank=True, null=True)),
                ("guest_count", models.PositiveIntegerField(blank=True, null=True)),
                ("estimated_budget", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("conversation_summary", models.TextField(blank=True)),
                ("qualification_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("stage", models.CharField(choices=[("new", "New Lead"), ("contacted", "Contacted"), ("qualified", "Qualified"), ("visit_scheduled", "Visit Scheduled"), ("proposal_sent", "Proposal Sent"), ("negotiation", "Negotiation"), ("won", "Won"), ("lost", "Lost")], default="new", max_length=20)),
                ("sentiment", models.CharField(blank=True, choices=[("positive", "Positive"), ("neutral", "Neutral"), ("negative", "Negative")], max_length=10)),
                ("last_interaction_at", models.DateTimeField(blank=True, null=True)),
                ("assigned_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_leads", to=settings.AUTH_USER_MODEL)),
                ("conversation", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="lead", to="conversation.conversation")),
                ("event_type", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="leads", to="venue.eventtype")),
                ("venue", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_set", to="venue.venue")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LeadActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("activity_type", models.CharField(choices=[("note", "Note"), ("stage_change", "Stage Change"), ("ai_action", "AI Action"), ("human_action", "Human Action")], max_length=20)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("lead", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="crm.lead")),
            ],
            options={
                "verbose_name_plural": "lead activities",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_at", models.DateTimeField()),
                ("status", models.CharField(choices=[("scheduled", "Scheduled"), ("confirmed", "Confirmed"), ("completed", "Completed"), ("cancelled", "Cancelled"), ("no_show", "No Show")], default="scheduled", max_length=20)),
                ("calendar_event_id", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("lead", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="visits", to="crm.lead")),
                ("venue", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_set", to="venue.venue")),
            ],
            options={
                "ordering": ["scheduled_at"],
            },
        ),
    ]
