# Generated by Django 6.0.8 on 2026-08-05 13:00

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarconnection',
            name='access_token',
            field=apps.core.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='calendarconnection',
            name='refresh_token',
            field=apps.core.fields.EncryptedTextField(),
        ),
    ]
