# Generated by Django 6.0.8 on 2026-08-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
