# Generated by Django 6.0.8 on 2026-08-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0011_proposal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadactivity",
            name="activity_type",
            field=models.CharField(choices=[("note", "Nota"), ("stage_change", "Mudança de Estágio"), ("ai_action", "Ação da IA"), ("human_action", "Ação Humana"), ("escalation", "Escalonamento"), ("error", "Erro")], max_length=20),
        ),
    ]
