# Generated by Django 6.0.8 on 2026-08-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
