# Generated by Django 6.0.8 on 2026-09-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0004_venue_whatsapp_business_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='photos_url',
            field=models.URLField(blank=True),
        ),
    ]
