# Generated by Django 6.0.8 on 2026-09-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("venue", "0005_venue_photos_url"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Image",
        ),
    ]
