# Generated by Django 6.0.8 on 2026-09-08 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0006_delete_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
