# Generated by Django 6.0.8 on 2026-08-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0002_message_unique_external_message_id_per_conversation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sender_type",
            field=models.CharField(choices=[("customer", "Cliente"), ("ai", "IA"), ("human", "Humano")], max_length=10),
        ),
    ]
