# Generated by Django 6.0.8 on 2026-09-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_alter_message_sender_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='error_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('sent', 'Enviada'), ('delivered', 'Entregue'), ('read', 'Lida'), ('failed', 'Falhou')], default='sent', max_length=10),
        ),
    ]
